# Generated by Django 6.0.6 on 2026-06-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dev_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worklist",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
