# Generated by Django 6.0.6 on 2026-06-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dev_app", "0002_alter_worklist_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worklist",
            name="complete",
            field=models.BooleanField(),
        ),
    ]
